version: '3'
services:
  db:
    image: postgres:15.2-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123321
      POSTGRES_DB: cities
    healthcheck:
      test: "pg_isready || exit 1"
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"

  app:
    image: demo-app:latest
    build:
      context: ./
    restart: always
    container_name: app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cities
    ports:
      - "8080:8080"
    depends_on:
      - "db"
