version: '3'
services:
  db:
    image: postgres:15.2-alpine
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123321
      POSTGRES_DB: cities
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready"
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: ./
    restart: always
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - "db"